extends: stylelint-config-standard
rules:
    indentation: 4
    rule-trailing-semicolon: null
    declaration-colon-space-before: null
    selector-list-comma-newline-after: null
    comment-empty-line-before: null
    number-leading-zero: null
    number-no-trailing-zeros: null
    function-url-quotes: none
    no-eol-whitespace: null
